import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import avatar from "@/assets/images/user.png";
import { Navbar } from "@/components/Navbar";
import { mainNavLinks } from "@/constants/NavLinks";
import { Footer } from "@/components/Footer";
import { footerNavLinks } from "@/constants/FooterLinks";
import { socialLinks } from "@/constants/SocialLinks";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const profileInfo = {
        name: "John Doe",
        email: "john@example.com",
        avatar: avatar,
    };
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Navbar
                    textLogo={{
                        text: "Spark",
                    }}
                    links={mainNavLinks}
                    profile={profileInfo}
                />
                {children}
                <Footer
                    companyInfo={{
                        name: "Spark",
                        address: "123 Tech Street, Silicon Valley, CA 94043",
                        email: "contact@spark.com",
                    }}
                    links={footerNavLinks}
                    socialLinks={socialLinks}
                />
            </body>
        </html>
    );
}
